sensor:
  - platform: shtcx
    address: 0x70
    update_interval: 60s
    temperature:
      name: "Temperature"
      filters:
              - median:
                  window_size: 5
                  send_every: 1
              - lambda: return x + id(temp_offset).state;
    humidity:
      name: "Humidity"
      filters:
        - median:
            window_size: 5
            send_every: 1
        - lambda: |-
            float result = x + id(hum_offset).state;
            if (result > 100) return 100; // Cap it so you don't get 105%
            if (result < 0) return 0;     // Cap it so you don't get -5%
            return result;

number:
  - platform: template
    name: "Temperature Offset"
    id: temp_offset
    icon: "mdi:calculator"
    unit_of_measurement: "°C"
    min_value: -20
    max_value: 20
    step: 0.1
    mode: box  # Or 'slider'
    optimistic: true
    restore_value: true
    initial_value: -8.7  # Start with your current known offset
  - platform: template
    name: "Humidity Offset"
    id: hum_offset
    icon: "mdi:water-percent"
    unit_of_measurement: "%"
    min_value: -20
    max_value: 20
    step: 1
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 0